<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'service_items_example' => '<p>Crear y administrar items de servicio es fácil. El único aspecto que debe tener en cuenta es que los "Items Generales" no pueden ser agendados de lado del cliente en modo autoAgenda. Módulos de servicio diferentes a "Item General" si pueden ser agendados o adquiridos por el cliente en modo autoAgenda y están directamente relacionados a una unidad de consumo como por ejemplo minutos. </p> <p>Como ejemplo podemos citar, un salón de belleza le permite a sus clientes agendar citas en tiempo real desde su página web. Los items de servicio en el panel de administración son creados bajo el módulo de servicio "Administrador de citas" porque es importante saber con exactitud el tiempo requerido para completar una cita  - esto con la finalidad de gestionar el sistema de calendario de manera eficiente. En este caso, cualquier actividad que consuma tiempo y que disponemos como agendable para que un cliente auto-agende, debe ser creado bajo el módulo de servicio "Administrador de Citas", por estar relacionado directamente a unidades de tiempo.</p><p>Continuando con el ejemplo, asumamos que durante el transcurso de la cita, el cliente decide aplicarse un tratamiento para el cabello, <strong></strong> Como este "Tratamientio" es solo una actividad complementaria que no requiere tiempo adicional al agendado, No debemos tratarla como un item agendable al interior del Administrador de Citas, y en su lugar lo configuramos como "Item General" - con el fin de poderlo agregar a la factura sin la necesidad de alterar el periodo de tiempo agendado.</p>',
    'contract_template_update' => '<p>Tengan en cuenta que cuando se actualiza una plantilla de contrato, las versiones online (las cuales puede encontrar en el panel de control) de contratos creados a partir de la plantilla actualizada, también se verán actualizados. Sin embargo, los que han sido enviados por email, los exportados y las versiones en PDF de contratos no serán actualizados, A menos que los vuelva a generar y notificar acorde.</p><p><strong>IMPORTANTE:</strong> Si usted cambia o remueve campos dinámicos para entrada de datos, cualquier contrato existente que haga uso de estos campos editados o eliminados, se verá impactado de manera directa y no podrá mostrar los datos de los campos dinámicos modificados o eliminados.</p>',
    'verify' => '<p>Un email y/o sms le ha sido enviado con un codigo PIN. Por favor ingrese el PIN recibido, en el campo inferior, para verificar su identidad.</p>',
    'business_address' => '<p>La dirección Corporativa o de Negocio es la informacion que el administrador del perfil desea presentar a sus clientes y personas en general y será usada en los documentos oficiales relacionados con el perfil, los mismos incluyen facturas, cotizaciones, notas de crédito/abonos, correos electrónicos y los pie de página de algunos otros documentos.</p>',
    'business_shipping_billing_address' => 'La dirección de envío y de facturación es usada sólo con propósitos administrativos y será usada específicamente para estos fines por parte de :BUSINESSNAME',
    'profile_create_did_number' => '<p>Por favor seleccione un número telefónico entrante para asignarle a este perfil. Importante anotar que cada número tiene características diferentes. Si desea enviar mensajes SMS, asegúrese de que el número DID esté habilitado para enviar mensajes de texto SMS. Si necesita procesar llamadas de voz, por favor asegúrese de que el número DID tenga habilitada la opción para hacer y/o recibir llamadas de voz.</p>',
    'logo_is_optional_on_edit' => '<p>Solo explore y seleccione un archivo con su logo si desea cambiar el logo actual.</p>',
    'long_billing_footer_text_can_be_edited' => 'El texto extenso de pie de página para facturas, notas de crédito y cotizaciones, puede ser actualizado dando click sobre el botón de editar',
    'invoice_status_new' => 'La factura actual no tiene estatus definido y aún no se ha podido guardar.',
    'quotation_status_new' => 'La cotización actual no tiene estatus definido y aún no se ha podido guardar.',
    'quotation_status_draft' => 'La cotización ha sido creada y un número <u>único</u> de cotización le ha sido asignado. El número asignado a una cotización <b>no puede ser reutilizado</b>. Cotizaciones con estatus de <b>BORRADOR</b> pueden aún ser editadas o cambiadas. Una vez que la cotización es <b>aceptada o convertida a factura </b>, no le podrá hacer cambios a la cotización.',
    'invoice_status_draft' => 'La factura ha sido creada y un número <u>único</u> de facturación le ha sido asignado. El número asignado a una factura <b>no puede ser reutilizado</b>. Facturas con estatus de <b>BORRADOR</b> pueden aún ser editadas o cambiadas. Una vez que el estatus de una factura se actualice a <b>PROTEGIDO,</b> ya no admitirá cambios.',
    'credit_note_status' => 'Para que una nota de crédito/abono surta efecto, su estatus debe ser actualizado a PROTEGIDO. Notas de crédito con estatus <i>BORRADOR</i> no serán tenidas en cuenta para efectos contables.',
    'contracts_explained' => '<p>Contract Builder es una gran herramienta para crear plantillas de contratos que puedan ser reutilizadas para fines diversos. Estos documentos soportan campos dinámicos y los contratos pueden ser modificados en tiempo real. Importante a tener en cuenta es actualizar los contratos relacionados cuando se agreguen o eliminen campos dinámicos.</p><p><b>Campos de ingreso</b> - Los campos dinámicos de ingreso pueden ser creados simplemente envolviendo la frase (que no debe contener espacios o caracteres especiales) entre Llaves dobles de la siguiente manera: <code>[[su_frase]]</code></p><p><b>UN EJEMPLO BASICO</b></p><p>Apreciado <code>[[nombre_de_cliente]]</code><br><br>Tenemos para la venta el producto<code>[[nombre_de_producto_en_venta]]</code> por un único pago de <code>[[precio_de_venta]]</code><br><br>Distribuido por: <code>[[nombre_de_vendedor]]</code></p>',
    'quote_exchange_rate' => 'IMPORTANTE: La moneda base es :profilecurrency. Haremos el intento de procesar la cotización en la moneda extranjera seleccionada, teniendo en cuenta las tasas vigentes de cambio. La tasa de cambio quedará fija y aplicada a la cotización, en el momento en que sea electrónicamente aceptada o si la cotización es convertida a factura.',
    'exchange_rate_notice_on_export' => 'IMPORTANTE: Las cifras cotizadas en :foreigncurrency son solo indicativas y podrían fluctuar dependiendo del cambio entre <br> :homecurrency/:foreigncurrency. Requerimos que los pagos se acrediten y procesen en la cantidad equivalente para nuestra moneda :homecurrency.',
    'note_credit_notes' => 'Tener en cuenta: Las cantidades en las notas de crédito/abonos deben ser procesadas con los impuestos incluidos',
    'manual_payments' => 'Importante: Los pagos en línea no pueden ser procesados en nombre de sus clientes. Esta sección es para procesar pagos que ya se hayan recibido.',
    'subscription_exchange_rate' => 'IMPORTANTE: La divisa de referencia es :profilecurrency. Haremos un intento por estimar el cambio en la moneda seleccionada, basando el cálculo en la tasa de referencia vigente. Las cifras estimadas en moneda extranjera serán mostradas sólo en la factura de la suscripción. Todas las cantidades segurirán siendo facturadas y procesadas en :profilecurrency',
    'service_package' => 'Los planes de servicio le permiten administrar sistematizadamente estos recursos a sus clientes directos. Múltiples planes con diversas configuraciones pueden ser ofrecidos a sus clientes.',
    'note_subscriptions' => 'Todos los valores ingresados deben agregarse sin impuestos incluidos',
    'airtime_explained' => '<p>Importante anotar que el balance de crédito no se deduce en forma automática del balance de su cuenta, cada cuenta de perfil tiene una "billetera de crédito" por separado. La recarga de saldo para surtir esta "billetera" se debe cargar desde un balance de cuenta.</p><p>Los propietarios del perfil pueden abonar pagos a sus cuentas, Pero como tenemos otras instancias financieras que necesariamente deben ser tenidas en cuenta; como suscripciones, facturas, notas de crédito, sumado al cálculo de impuestos para estos registros, tenemos que asegurarnos de en efecto facturar transacciones para su "billetera de crédito" desde su cuenta de perfil.</p><p>Entonces cuando una cuenta de perfil desea agregar crédito a su "billetera", el propietario de la cuenta (o quien lo administre) debe comprar crédito haciendo uso del balance de la cuenta de perfil como medio de pago.</p>',
    'airtime_explained_alt' => '<p>Importante anotar que el balance de crédito para su "billetera de crédito/saldo" no se deduce en forma automática del balance de su cuenta, ya que su perfil tiene una "billetera de crédito" por separado. La compra de crédito debe hacerse desde el balance de su cuenta. De esta manera cuando desee recargar saldo o crédito a su "billetera", debe hacer la compra haciendo uso del balance de su cuenta como forma de pago.</p>',
    'did_defaults_profile' => 'Los números DID son números virtuales que le permiten, dependiendo del plan y el proveedor, enviar y recibir sistematisadamente mensajes de texto y/o llamadas de voz, desde y hacía su panel de control. También le permite a los destinatarios de mensajes de texto, replicar directamente a su panel de usuario (algunos países tienen restricciones sobre ciertas funcionalidades listadas). Tenga presente que no todos los países soportan números virtuales.',
    'did_defaults' => 'Cuando un mensaje de texto es enviado, el sistema intentará buscar por el primer número DID asignado disponible con capacidad para enviar textos SMS. El mismo principio aplica para procesar llamadas. Cuando se inicia una petición de llamada, el sistema automaticamente buscará el primer número DID disponible con capacidad para procesar llamadas. Por eso resulta favorable asignar un mismo número con capacidad para procesar tanto voz como textos. Sin embargo en algunos países los números DID no pueden procesar ambas funciones al mismo  tiempo. Teniendo esto último en cuenta, El sistema le permite asignar un número para voz y otro para textos. Resumiendo, tenga presente que si un número no tiene capacidad para envío de textos, entonces no podrá enviar mensajes SMS. Lo mismo aplica para procesar llamadas de voz.',
    'payment_status' => 'El estatus actual de este pago es BORRADOR. Los documentos deben tener estatus PROTEGIDO para que surtan fecto.',
    'join_how_it_works' => 'Una vez diligencie el formulario a continuaci&oacute;n, tendr&aacute; acceso instant&aacute;neo a su cuenta de perfil y podr&aacute; hacer uso del plan seleccionado. En su email encontrar&aacute; algunos correos que incluyen instrucciones adicionales y las credenciales para ingresara a la plataforma.',

];
